spring.application.name=ShareBiteBackend

# 1. DATABASE CONFIGURATION (MySQL)

spring.datasource.url=jdbc:mysql://localhost:3306/sharebite_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=jeeva123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. JPA & HIBERNATE CONFIGURATION

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# 3. SERVER CONFIGURATION

# port for backend (React frontend often runs on 3000)
server.port=8080


# JWT Configuration

sharebite.app.jwtSecret=SuperSecure2025SecretKeyForFoodApp
sharebite.app.jwtExpirationMs=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=sharebite02@gmail.com
spring.mail.password=gdup ijrq hyum bgty

# Protocol Settings for Gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com